-- 1. Consultar informações sobre torneios, modalidades e grupos

SELECT 
    T.DESCRICAO AS TORNEIO_DESCRICAO,
    T.STATUS AS TORNEIO_STATUS,
    T.DATA_INICIO AS TORNEIO_INICIO,
    T.DATA_FIM AS TORNEIO_FIM,
    M.NOME AS MODALIDADE_NOME,
    G.NOME AS GRUPO_NOME
FROM 
    TORNEIO T
JOIN 
    MODALIDADE M ON M.TORNEIO_ID = T.ID
JOIN 
    GRUPO G ON G.MODALIDADE_ID = M.ID
WHERE 
    T.STATUS = 'EM_ANDAMENTO';


--Consultar atletas com suas equipes e modalidades

SELECT 
    A.NOME AS ATLETA_NOME,
    A.SEXO AS ATLETA_SEXO,
    A.NASCIMENTO AS ATLETA_NASCIMENTO,
    E.NOME AS EQUIPA_NOME,
    M.NOME AS MODALIDADE_NOME
FROM 
    ATLETA A
JOIN 
    EQUIPA E ON A.EQUIPA_ID = E.ID
JOIN 
    MODALIDADE M ON E.MODALIDADE_ID = M.ID;



	--Consultar partidas e suas equipes
	SELECT 
    P.DATA_HORA AS PARTIDA_DATA_HORA,
    E1.NOME AS EQUIPA1_NOME,
    E2.NOME AS EQUIPA2_NOME,
    P.RESULTADO AS PARTIDA_RESULTADO
FROM 
    PARTIDA P
JOIN 
    EQUIPA E1 ON P.EQUIPA1_ID = E1.ID
JOIN 
    EQUIPA E2 ON P.EQUIPA2_ID = E2.ID;


-- Consultar classificação por grupo e modalidade
SELECT 
    M.NOME AS MODALIDADE_NOME,
    G.NOME AS GRUPO_NOME,
    E.NOME AS EQUIPA_NOME,
    C.PONTOS,
    C.VITORIAS,
    C.DERROTAS,
    C.GOLS_PRO,
    C.GOLS_CONTRA
FROM 
    CLASSIFICACAO C
JOIN 
    GRUPO_POR_EQUIPA GPE ON C.GRUPO_POR_EQUIPA_ID = GPE.ID
JOIN 
    GRUPO G ON G.ID = GPE.GRUPO_ID
JOIN 
    EQUIPA E ON E.ID = GPE.EQUIPA_ID
JOIN 
    MODALIDADE M ON M.ID = C.MODALIDADE_ID
ORDER BY 
    C.PONTOS DESC, C.SALDO_GOLS DESC;

	-- Consultar estatísticas dos atletas em partidas específicas

SELECT 
    P.DATA_HORA AS PARTIDA_DATA_HORA,
    A.NOME AS ATLETA_NOME,
    E.NOME AS EQUIPA_NOME,
    S.GOLS,
    S.ASSISTENCIAS,
    S.FALTAS_COMETIDAS,
    S.CARTOES_AMARELOS,
    S.CARTOES_VERMELHOS
FROM 
    ESTATISTICA S
JOIN 
    ATLETA A ON S.ATLETA_ID = A.ID
JOIN 
    EQUIPA E ON S.EQUIPA_ID = E.ID
JOIN 
    PARTIDA P ON S.PARTIDA_ID = P.ID;
