DROP DATABASE GERENCIAMENTO;

-- Altere para o banco de dados master, para poder executar o comando de desconexão
USE master;

-- Altere o banco de dados para modo de restrição
ALTER DATABASE GERENCIAMENTO SET SINGLE_USER WITH ROLLBACK IMMEDIATE;

-- Agora você pode excluir o banco de dados
DROP DATABASE GERENCIAMENTO;

CREATE DATABASE GERENCIAMENTO;
USE GERENCIAMENTO;

CREATE TABLE TORNEIO (
    ID INT PRIMARY KEY IDENTITY(1,1),
    DESCRICAO TEXT,
    STATUS VARCHAR(20) CHECK (STATUS IN ('PLANEJADO', 'EM_ANDAMENTO', 'FINALIZADO')),
    DATA_INICIO DATETIME,
    DATA_FIM DATETIME
);


CREATE TABLE MODALIDADE (
    ID INT PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO TEXT, 
    PONTO_POR_VITORIA INT, 
    PONTO_POR_EMPATE INT, 
    QUANTIADE_DE_JOGADORES_POR_EQUIPE INT, 
    QUANTIADE_DE_JOGADORES_RESERVA INT, 
    TIPO VARCHAR(10) CHECK (TIPO IN ('MASCULINO', 'FEMININO', 'UNISSEX')), 
    TORNEIO_ID INT, 
    FOREIGN KEY (TORNEIO_ID) REFERENCES TORNEIO(ID)
);

CREATE TABLE GRUPO (
    ID INT PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(50) NOT NULL, 
    MODALIDADE_ID INT NOT NULL, 
    FOREIGN KEY (MODALIDADE_ID) REFERENCES MODALIDADE(ID) ON DELETE CASCADE
);

CREATE TABLE EQUIPA (
    ID INT PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(100) NOT NULL, 
    DESCRICAO TEXT, 
    MODALIDADE_ID INT NOT NULL, 
    FOREIGN KEY (MODALIDADE_ID) REFERENCES MODALIDADE(ID) 
);


CREATE TABLE GRUPO_POR_EQUIPA (
    ID INT PRIMARY KEY IDENTITY(1,1),
    GRUPO_ID INT NOT NULL,
    EQUIPA_ID INT NOT NULL,
    FOREIGN KEY (GRUPO_ID) REFERENCES GRUPO(ID) ON DELETE CASCADE,
    FOREIGN KEY (EQUIPA_ID) REFERENCES EQUIPA(ID) ON DELETE CASCADE
);

CREATE TABLE ATLETA (
    ID INT PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(100) NOT NULL, 
    NASCIMENTO DATETIME NOT NULL, 
    PAIS VARCHAR(100), 
    ESTADO VARCHAR(100),
    CIDADE VARCHAR(100),
	SEXO CHAR(1),
    EQUIPA_ID INT, 
    FOREIGN KEY (EQUIPA_ID) REFERENCES EQUIPA(ID) ON DELETE SET NULL
);

CREATE TABLE FASE (
    ID INT PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(50) NOT NULL, 
    ORDEM INT NOT NULL,  
    MODALIDADE_ID INT NOT NULL, 
    DATA_INICIO DATETIME NOT NULL, 
    DATA_FIM DATETIME NOT NULL, 
    FOREIGN KEY (MODALIDADE_ID) REFERENCES MODALIDADE(ID) ON DELETE CASCADE
);

CREATE TABLE PARTIDA (
    ID INT PRIMARY KEY IDENTITY(1,1),
    FASE_ID INT NOT NULL,
    GRUPO_ID INT,
    EQUIPA1_ID INT NOT NULL, 
    EQUIPA2_ID INT NOT NULL, 
    DATA_HORA DATETIME NOT NULL, 
    RESULTADO VARCHAR(50), 
    FOREIGN KEY (FASE_ID) REFERENCES FASE(ID) ON DELETE NO ACTION,
    FOREIGN KEY (GRUPO_ID) REFERENCES GRUPO(ID) ON DELETE NO ACTION,
    FOREIGN KEY (EQUIPA1_ID) REFERENCES EQUIPA(ID) ON DELETE NO ACTION,
    FOREIGN KEY (EQUIPA2_ID) REFERENCES EQUIPA(ID) ON DELETE NO ACTION
);

CREATE TABLE CALENDARIO (
    ID INT PRIMARY KEY IDENTITY(1,1),
    PARTIDA_ID INT NOT NULL, 
    DATA_HORA DATETIME NOT NULL, 
    DESCRICAO TEXT, 
    FOREIGN KEY (PARTIDA_ID) REFERENCES PARTIDA(ID) ON DELETE CASCADE
);
CREATE TABLE CLASSIFICACAO (
    ID INT PRIMARY KEY IDENTITY(1,1),
    MODALIDADE_ID INT NOT NULL, 
    GRUPO_POR_EQUIPA_ID INT NOT NULL, 
    PONTOS INT DEFAULT 0, 
    VITORIAS INT DEFAULT 0, 
    EMPATES INT DEFAULT 0, 
    DERROTAS INT DEFAULT 0,
    GOLS_PRO INT DEFAULT 0, 
    GOLS_CONTRA INT DEFAULT 0, 
    SALDO_GOLS AS (GOLS_PRO - GOLS_CONTRA) PERSISTED,  -- Correção do uso de PERSISTED
    FOREIGN KEY (MODALIDADE_ID) REFERENCES MODALIDADE(ID),
    FOREIGN KEY (GRUPO_POR_EQUIPA_ID) REFERENCES GRUPO_POR_EQUIPA(ID)
);



CREATE TABLE ESTATISTICA (
    ID INT PRIMARY KEY IDENTITY(1,1),
    PARTIDA_ID INT NOT NULL, 
    EQUIPA_ID INT,
    ATLETA_ID INT, 
    GOLS INT DEFAULT 0,
    ASSISTENCIAS INT DEFAULT 0,
    CHUTES_AO_GOL INT DEFAULT 0,
    FALTAS_COMETIDAS INT DEFAULT 0, 
    CARTOES_AMARELOS INT DEFAULT 0, 
    CARTOES_VERMELHOS INT DEFAULT 0, 
    POSSE_BOLA_PERCENTUAL DECIMAL(5, 2), 
    PASSES_COMPLETOS INT DEFAULT 0,
    FOREIGN KEY (PARTIDA_ID) REFERENCES PARTIDA(ID) ON DELETE CASCADE,
    FOREIGN KEY (EQUIPA_ID) REFERENCES EQUIPA(ID) ON DELETE CASCADE,
    FOREIGN KEY (ATLETA_ID) REFERENCES ATLETA(ID) ON DELETE CASCADE
);



